# Generated by Django 3.1.2 on 2020-10-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
